name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  params:
    description: 'parameters'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.params }}
